### ISSUE TITLE
Build Failure: File I/O Error

### ISSUE THREAD

**Issue by mistergibson** [tilialabs/qtjambi5#3]
This reproduces the issue:

ant all
Buildfile: /home/mistergibson/Documents/Development/qmlscraps/qtjambi5.old/build.xml

log:
     [echo] Build logged to build_2017-12-24_22-00-22.log

check.antcontrib:

antcontrib.systemcopy:

get.antcontrib:

source.antcontrib:

check-kdephonon:

setup-properties:

setenv:

jar.qtjambi-util:

jar_init:

compile:
     [echo] Compiling java classes: /home/mistergibson/Documents/Development/qmlscraps/qtjambi5.old/src/java/qtjambi-util excludes: ${module.excludes}

copy-resources:

makejar.qtjambi-util:
     [echo] Creating JAR file: qtjambi-util.jar   excludes: 
      [jar] Building jar: /home/mistergibson/Documents/Development/qmlscraps/qtjambi5.old/jars/qtjambi-util.jar

copy-src-resources:

makesrcjar.qtjambi-util:
     [echo] Creating SRCJAR file: qtjambi-util.jar   excludes: 
      [jar] Building jar: /home/mistergibson/Documents/Development/qmlscraps/qtjambi5.old/jars/qtjambi-util-src.jar

jar.ant-qtjambi:

jar_init:

compile:
     [echo] Compiling java classes: /home/mistergibson/Documents/Development/qmlscraps/qtjambi5.old/src/java/ant-qtjambi excludes: ${module.excludes}

copy-resources:

makejar:
     [echo] Creating JAR file: ant-qtjambi.jar   excludes: ${jar.excludes}
      [jar] Building jar: /home/mistergibson/Documents/Development/qmlscraps/qtjambi5.old/jars/nobundle/ant-qtjambi.jar

copy-src-resources:

makesrcjar:
     [echo] Creating SRCJAR file: ant-qtjambi.jar   excludes: ${jar.excludes}
      [jar] Building jar: /home/mistergibson/Documents/Development/qmlscraps/qtjambi5.old/jars/nobundle/ant-qtjambi-src.jar

init.taskdef:
Trying to override old definition of datatype file

init:
[qtjambi-initialize] sep: / (auto-detect)
[qtjambi-initialize] psep: : (auto-detect)
[qtjambi-initialize] jambi.directory: /home/mistergibson/Documents/Development/qmlscraps/qtjambi5.old (already set to same value)
[qtjambi-initialize] qtjambi.osname: linux64 (auto-detected)
[qtjambi-initialize] JAVA_HOME is set: /usr/lib/jvm/java-8-oracle
[qtjambi-initialize] java.home.target: /usr/lib/jvm/java-8-oracle (from envvar:JAVA_HOME)
[qtjambi-initialize] java.osarch.target: linux (auto-detected)
[qtjambi-initialize] java.oscpu: amd64 (detected from JVM property:os.arch)
[qtjambi-initialize] java.oscpu.target: amd64 (inherited from ${java.oscpu})

init.build:
[qtjambi-initialize-build] sep: / (already set to same value)
[qtjambi-initialize-build] psep: : (already set to same value)
[qtjambi-initialize-build] jambi.directory: /home/mistergibson/Documents/Development/qmlscraps/qtjambi5.old (already set to same value)
[qtjambi-initialize-build] jambi.directory.abspath: /home/mistergibson/Documents/Development/qmlscraps/qtjambi5.old
[qtjambi-initialize-build] qtjambi.qt.bindir: <notset>
[qtjambi-initialize-build] qtjambi.qt.libdir: <notset>
[qtjambi-initialize-build] qtjambi.qt.includedir: <notset>
[qtjambi-initialize-build] qtjambi.qt.pluginsdir: <notset>
[qtjambi-initialize-build] qtjambi.qt.importsdir: <notset>
[qtjambi-initialize-build] qtjambi.qt.qmlmodulesdir: <notset>
[qtjambi-initialize-build] qtjambi.phonon.includedir: <notset>
[qtjambi-initialize-build] qtjambi.phonon.libdir: <notset>
[qtjambi-initialize-build] qtjambi.phonon.pluginsdir: <notset>
[qtjambi-initialize-build] qtjambi.phonon.kdephonon-path: <empty-string>
[qtjambi-initialize-build] qtjambi.qt.qmake: qmake (default)
[qtjambi-initialize-build] qtjambi.qt.qmake.abspath: /usr/bin/qmake (auto-detected)
[qtjambi-initialize-build] qtjambi.osname: linux64 (detected: linux64) (already set to same value)
[qtjambi-initialize-build] qtjambi.compiler: gcc (available compilers: gcc; auto-detected)
[qtjambi-initialize-build] exec.strip: <notset>
[qtjambi-initialize-build] JAVA_HOME is set: /usr/lib/jvm/java-8-oracle
[qtjambi-initialize-build] java.home.target: /usr/lib/jvm/java-8-oracle (already set to same value)
[qtjambi-initialize-build] java.osarch.target: linux (already set to same value)
[qtjambi-initialize-build] java.oscpu: amd64 (already set to same value)
[qtjambi-initialize-build] java.oscpu.target: amd64 (already set to same value)
[qtjambi-initialize-build] tools.qt.bindir: /usr/lib/x86_64-linux-gnu/qt5/bin (already set to same value)
[qtjambi-initialize-build] tools.qt.libdir: /usr/lib/x86_64-linux-gnu/qt5/lib (already set to same value)
[qtjambi-initialize-build] tools.qt.qmake: qmake (inherited from ${qtjambi.qt.qmake})
[qtjambi-initialize-build] tools.qt.qmake.abspath: /usr/lib/x86_64-linux-gnu/qt5/bin/qmake (auto-detected)

BUILD FAILED
/home/mistergibson/Documents/Development/qmlscraps/qtjambi5.old/build.xml:114: java.lang.NullPointerException
	at java.io.File.<init>(File.java:277)
	at org.qtjambi.tools.ant.InitializeBuildTask.executeInitialize(InitializeBuildTask.java:449)
	at org.qtjambi.tools.ant.AbstractInitializeTask.execute(AbstractInitializeTask.java:60)
	at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:293)
	at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
	at org.apache.tools.ant.Task.perform(Task.java:348)
	at org.apache.tools.ant.Target.execute(Target.java:435)
	at org.apache.tools.ant.Target.performTasks(Target.java:456)
	at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1405)
	at org.apache.tools.ant.Project.executeTarget(Project.java:1376)
	at org.apache.tools.ant.helper.DefaultExecutor.executeTargets(DefaultExecutor.java:41)
	at org.apache.tools.ant.Project.executeTargets(Project.java:1260)
	at org.apache.tools.ant.Main.runBuild(Main.java:853)
	at org.apache.tools.ant.Main.startAnt(Main.java:235)
	at org.apache.tools.ant.launch.Launcher.run(Launcher.java:285)
	at org.apache.tools.ant.launch.Launcher.main(Launcher.java:112)

I cannot for the life of me figure out why this is happening.

**Comment by ZanSara** [comment]
Usually such NPE are due to wrong paths. Are you sure that `jambi.directory` path is correct? Have you set the environment variables correctly?

My `init.build` output, for example, is:
```init.build:
[qtjambi-initialize-build] sep: / (already set to same value)
[qtjambi-initialize-build] psep: : (already set to same value)
[qtjambi-initialize-build] jambi.directory: /opt/dev/qtjambi5 (already set to same value)
[qtjambi-initialize-build] jambi.directory.abspath: /opt/dev/qtjambi5
[qtjambi-initialize-build] QTDIR is set: /opt/dev/qt-everywhere-opensource-src-5.6.2/qtbase
[qtjambi-initialize-build] qtjambi.qt.bindir: /opt/dev/qt-everywhere-opensource-src-5.6.2/qtbase/bin (from envvar:QTDIR)
[qtjambi-initialize-build] qtjambi.qt.libdir: /opt/dev/qt-everywhere-opensource-src-5.6.2/qtbase/lib (from envvar:QTDIR)
[qtjambi-initialize-build] qtjambi.qt.includedir: /opt/dev/qt-everywhere-opensource-src-5.6.2/qtbase/include (from envvar:QTDIR)
[qtjambi-initialize-build] qtjambi.qt.pluginsdir: <notset>
[qtjambi-initialize-build] qtjambi.qt.importsdir: <notset>
[qtjambi-initialize-build] qtjambi.qt.qmlmodulesdir: <notset>
[qtjambi-initialize-build] qtjambi.phonon.includedir: /opt/dev/qt-everywhere-opensource-src-5.6.2/qtbase/include (inherited from ${qtjambi.qt.includedir})
[qtjambi-initialize-build] qtjambi.phonon.libdir: /opt/dev/qt-everywhere-opensource-src-5.6.2/qtbase/lib (inherited from ${qtjambi.qt.libdir})
[qtjambi-initialize-build] qtjambi.phonon.pluginsdir: <notset>
[qtjambi-initialize-build] qtjambi.phonon.kdephonon-path: <empty-string>
[qtjambi-initialize-build] qtjambi.qt.qmake: qmake (default)
[qtjambi-initialize-build] qtjambi.qt.qmake.abspath: /usr/local/Qt-5.6.2/bin/qmake (auto-detected)
[qtjambi-initialize-build] qtjambi.osname: linux64 (detected: linux64) (already set to same value)```
